// <auto-generated />
using System;
using BeautyStore.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeautyStore.Infra.Data.Migrations
{
    [DbContext(typeof(BeautyStoreDbContext))]
    partial class BeautyStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("BeautyStore.Domain.Entities.Categoria", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.HasKey("Id");

                b.ToTable("Categorias");
            });

            modelBuilder.Entity("BeautyStore.Domain.Entities.Produto", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CategoriaId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<int>("Estoque")
                    .HasColumnType("int");

                b.Property<string>("Imagem")
                    .IsRequired()
                    .HasColumnType("nvarchar(1000)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<decimal>("Preco")
                    .HasColumnType("decimal(18,2)");

                b.Property<Guid>("VendedorId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("CategoriaId");

                b.HasIndex("VendedorId");

                b.ToTable("Produtos");
            });

            modelBuilder.Entity("BeautyStore.Domain.Entities.Vendedor", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("IsProprietario")
                    .HasColumnType("bit");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.HasKey("Id");

                b.ToTable("Vendedores");
            });

            modelBuilder.Entity("BeautyStore.Domain.Entities.Produto", b =>
            {
                b.HasOne("BeautyStore.Domain.Entities.Categoria", "Categoria")
                    .WithMany()
                    .HasForeignKey("CategoriaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("BeautyStore.Domain.Entities.Vendedor", "Vendedor")
                    .WithMany()
                    .HasForeignKey("VendedorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Categoria");

                b.Navigation("Vendedor");
            });
#pragma warning restore 612, 618
        }
    }
}
